version: "3"
services:
  coordinator:
    image: basho/riak-ts
    ports:
      - "8087:8087"
      - "8098:8098"
    environment:
      - CLUSTER_NAME=riakts
    labels:
      - "com.basho.riak.cluster.name=riakts"
    volumes:
      - ./data:/var/lib/riak
      - ./logs:/var/log/riak
      - ./schemas:/etc/riak/schemas/
    networks:
      net:
        ipv4_address: 10.3.0.2
  member:
    image: basho/riak-ts
    ports:
      - "8087"
      - "8098"
    labels:
      - "com.basho.riak.cluster.name=riakts"
    depends_on:
      - coordinator
    environment:
      - CLUSTER_NAME=riakts
      - COORDINATOR_NODE='10.3.0.2'
    networks:
      net:
        ipv4_address: 10.3.0.3
  nodeapp:
    image: nbinik/healthapp
    restart: always 
    ports:
      - "5000:8080"
    depends_on:
      - coordinator
    environment:
      - RIAK_ADDRESS='10.3.0.2:8087'
      - RIAK_RECONECT_ATTEMPTS=5
    volumes:
      - /home/nikita/secrets:/home/node/app/secrets
    networks:
      net:
        ipv4_address: 10.3.0.4
  nginx:
    image: nginx:1.15-alpine
    restart: unless-stopped
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    ports:
      - "8080:8080"
      - "443:443"
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    networks:
      net:
        ipv4_address: 10.3.0.5
  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    networks:
      net:
        ipv4_address: 10.3.0.6
networks:
  net:
    ipam:
     config:
       - subnet: 10.3.0.0/16

